### ISSUE TITLE
No module named 'PolyAcaller'

### ISSUE THREAD

**Issue by liuyujie0136** [ZhaiLab-SUSTech/FLEPSeq#1]
An error occurred when running "PolyACaller.py" script:

```
ModuleNotFoundError: No module named 'PolyAcaller'
```

As far as I know, no module with this name can be found on PyPI, nor can it be found in other materials provided in this repo.

So, how to run this script according to the pipeline in _Nat. Protoc._?

Best regards,

**Comment by WeipengMO** [comment]
fixed by [f04854e](https://github.com/ZhaiLab-SUSTech/FLEPSeq/commit/f04854ec263ca9923ae5bffdc82a2dc46d8cb9bc)
