### ISSUE TITLE
something wrong with PolyACaller.py

### ISSUE THREAD

**Issue by seven1112233** [ZhaiLab-SUSTech/FLEPSeq#2]
hi, 
when identify polyA tail and estimate its length using PolyACaller.py, something wrong happen!
![image](https://user-images.githubusercontent.com/71070001/224481782-03ade08a-9fdf-43b6-a9a8-51a545259f46.png)
could you tell me how to sovle this problem? 
thank you very much!

**Comment by WeipengMO** [comment]
Hi @seven1112233 , You need to basecall your fast5 files first. You can use the `--fast5_out` option in guppy to do that. This is mentioned in the readme document of this repository. Please check it out and let me know if you have any questions. Thank you for using FLEPSeq!

Best,
Weipeng

**Comment by LongYuan0529** [comment]
Hi～For my data, I have already have fast5 and fastq file when I logout my data, why I have to basecall my fast5 files again?

**Comment by WeipengMO** [comment]
Hi @LongYuan0529, 

Re-basecalling is not necessary if your FAST5 files contained the basecalled information. You can check your FAST5 files whether were basecalled or not by using the `h5ls` tool.

I hope this help.

Best,
Weipeng
