### ISSUE TITLE
Hello，when I run the code “polyAcaller.py”, the

### ISSUE THREAD

**Issue by LongYuan0529** [ZhaiLab-SUSTech/FLEPSeq#4]

**Comment by LongYuan0529** [comment]
the error is "unsupported operand type(s) for +: 'NoneType' and 'str'", what should I do? The txt data is right.

**Comment by WeipengMO** [comment]
Could you provide more details? I am not sure where this error came from. I recommend you to run the demo data first to make sure your environment is right.

**Comment by LongYuan0529** [comment]
Hello, I am very happy to receive your Email, I have already solve my problems.
Thanks

2023-06-09 00:22:53"weipeng" ***@***.***>写道：

Could you provide more details? I am not sure where this error came from. I recommend you to run the demo data first to make sure your environment is right.
